base:
  project: Adult-Census-Income-prediction
  random_state: 42
  target_col: expenses

data_source:
  s3_source: data_given/adult.csv


load_data:
  raw_dataset: data/raw/adult.csv


preprocessing:
  processed: data/processed/adult_processed.csv

final_data:
  transformed_data: data/transformed/adult_transformed.csv


split_data:
  train_path: data/split_data/train_adult.csv
  test_path: data/split_data/test_adult.csv
  split_ratio: 0.2

